### PR TITLE
Reverted the version.ts changes and creating a new release

### PR DESCRIPTION
**Pull request by kathirsvn**
**What this PR does**:
This PR reverts the changes done to remove `version.ts` file in [this commit](https://github.com/stargate/stargate-mongoose/commit/ea5b4976d2544a40f966b8a3ae2d3282e4ff7932).

The reason for reverting is that:
```text
After the changes done to remove the verstion.ts file especially the change done in package.json (`resolveJsonModule: true`)  in tsconfig.json, the packaging is done differently and the apps using the library fails

- https://www.npmjs.com/package/stargate-mongoose/v/0.2.0-ALPHA-5?activeTab=code (index.js is packaged under dist directly) 
- https://www.npmjs.com/package/stargate-mongoose/v/0.2.0-ALPHA-7?activeTab=code (index.js is packaged under src under dist)

_Error from the apps using stargate-mongoose latest version:
Error: Cannot find module '/node_modules/stargate-mongoose/dist/index.js'. Please verify that the package.json has a valid "main" entry_

I tried to change main property inside package.json from "main": "dist/index.js"  to "main": "dist/src/index.js" but that didn't help.
```

**Checklist**
- [X] Changes manually tested
- [X] Automated Tests added/updated
- [X] Documentation added/updated
- [X] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Review by vkarpov15 — APPROVED** [review]
I'd recommend fixing the lint warnings, but not worth blocking the release. LGTM :+1:

**Review by jeffreyscarpenter — APPROVED** [review]

**Comment by kathirsvn** [comment]
> I'd recommend fixing the lint warnings, but not worth blocking the release. LGTM 👍

@vkarpov15 My bad, missed it. I'll fix it in the next commit.
